## Data Loading

In [1]:
import pandas as pd

file_path = '/content/uber_trips.parquet'
df = pd.read_parquet(file_path)
df.head()

,request_datetime,on_scene_datetime,pickup_datetime,dropoff_datetime,PULocationID,DOLocationID,trip_miles,trip_time,tolls,tips,driver_pay,PUBorough,PUZone,DOBorough,DOZone,time_from_request_to_pickup,day_of_week,hour_bucket
0,2026-01-01 00:50:37,2026-01-01 00:52:31,2026-01-01 00:54:30,2026-01-01 01:13:23,262,79,4.30,1133,0.0,0.00,21.10,Manhattan,Yorkville East,Manhattan,East Village,114.0,Thursday,0
1,2026-01-01 00:09:12,2026-01-01 00:12:17,2026-01-01 00:12:39,2026-01-01 00:22:42,195,52,1.89,604,0.0,0.00,9.10,Brooklyn,Red Hook,Brooklyn,Cobble Hill,185.0,Thursday,0
2,2026-01-01 00:16:16,2026-01-01 00:29:33,2026-01-01 00:31:34,2026-01-01 00:55:21,25,181,1.84,1427,0.0,2.67,21.94,Brooklyn,Boerum Hill,Brooklyn,Park Slope,797.0,Thursday,0
3,2026-01-01 00:29:54,2026-01-01 00:36:04,2026-01-01 00:36:32,2026-01-01 01:02:28,162,113,2.84,1556,0.0,0.00,20.90,Manhattan,Midtown East,Manhattan,Greenwich Village North,370.0,Thursday,0
4,2026-01-01 00:07:33,2026-01-01 00:10:16,2026-01-01 00:11:14,2026-01-01 00:14:06,22,22,0.66,172,0.0,0.00,4.31,Brooklyn,Bensonhurst West,Brooklyn,Bensonhurst West,163.0,Thursday,0

## Average Time For Zone To Zone (Per Hour Per Day)

In [2]:
grouped_data = df.groupby(['PUZone', 'DOZone', 'hour_bucket', 'day_of_week'])
average_trip_time_by_route_time = grouped_data['trip_time'].mean().reset_index()

# Calculate the count of instances for each combination
trip_count_by_route_time = grouped_data.size().reset_index(name='trip_count')

# Merge the count into the average trip time DataFrame
average_trip_time_by_route_time = pd.merge(
    average_trip_time_by_route_time,
    trip_count_by_route_time,
    on=['PUZone', 'DOZone', 'hour_bucket', 'day_of_week'],
    how='left'
)

# Set trip_time to 0 where PUZone and DOZone are the same
average_trip_time_by_route_time.loc[average_trip_time_by_route_time['PUZone'] == average_trip_time_by_route_time['DOZone'], 'trip_time'] = 0

# Rename the 'trip_time' column to 'average_trip_time'
average_trip_time_by_route_time = average_trip_time_by_route_time.rename(columns={'trip_time': 'average_PU_to_DO_time'})

print(average_trip_time_by_route_time.head())
print(average_trip_time_by_route_time.shape)

                    PUZone                   DOZone  hour_bucket day_of_week  \
0  Allerton/Pelham Gardens  Allerton/Pelham Gardens            0      Friday
1  Allerton/Pelham Gardens  Allerton/Pelham Gardens            0      Monday
2  Allerton/Pelham Gardens  Allerton/Pelham Gardens            0    Saturday
3  Allerton/Pelham Gardens  Allerton/Pelham Gardens            0      Sunday
4  Allerton/Pelham Gardens  Allerton/Pelham Gardens            0    Thursday

   average_PU_to_DO_time  trip_count
0                    0.0          12
1                    0.0          11
2                    0.0          18
3                    0.0          13
4                    0.0          11
(3138392, 6)

In [3]:
# Merge 'average_PU_to_DO_time' back into the original DataFrame 'df'
df = pd.merge(
    df,
    average_trip_time_by_route_time[['PUZone', 'DOZone', 'hour_bucket', 'day_of_week', 'average_PU_to_DO_time']],
    on=['PUZone', 'DOZone', 'hour_bucket', 'day_of_week'],
    how='left'
)

print(df.head())
print(df.shape)

# Check for missing values after the merge
print("\nMissing values after merge:")
print(df.isnull().sum())

# Print 5 random rows with specified columns
print("\n5 random rows with relevant columns:")
print(df[['PUZone', 'DOZone', 'day_of_week', 'hour_bucket', 'average_PU_to_DO_time']].sample(5))

     request_datetime   on_scene_datetime     pickup_datetime  \
0 2026-01-01 00:50:37 2026-01-01 00:52:31 2026-01-01 00:54:30
1 2026-01-01 00:09:12 2026-01-01 00:12:17 2026-01-01 00:12:39
2 2026-01-01 00:16:16 2026-01-01 00:29:33 2026-01-01 00:31:34
3 2026-01-01 00:29:54 2026-01-01 00:36:04 2026-01-01 00:36:32
4 2026-01-01 00:07:33 2026-01-01 00:10:16 2026-01-01 00:11:14

     dropoff_datetime  PULocationID  DOLocationID  trip_miles  trip_time  \
0 2026-01-01 01:13:23           262            79        4.30       1133
1 2026-01-01 00:22:42           195            52        1.89        604
2 2026-01-01 00:55:21            25           181        1.84       1427
3 2026-01-01 01:02:28           162           113        2.84       1556
4 2026-01-01 00:14:06            22            22        0.66        172

   tolls  tips  driver_pay  PUBorough            PUZone  DOBorough  \
0    0.0  0.00       21.10  Manhattan    Yorkville East  Manhattan
1    0.0  0.00        9.10   Brooklyn          Red Hook   Brooklyn
2    0.0  2.67       21.94   Brooklyn       Boerum Hill   Brooklyn
3    0.0  0.00       20.90  Manhattan      Midtown East  Manhattan
4    0.0  0.00        4.31   Brooklyn  Bensonhurst West   Brooklyn

                    DOZone  time_from_request_to_pickup day_of_week  \
0             East Village                        114.0    Thursday
1              Cobble Hill                        185.0    Thursday
2               Park Slope                        797.0    Thursday
3  Greenwich Village North                        370.0    Thursday
4         Bensonhurst West                        163.0    Thursday

   hour_bucket  average_PU_to_DO_time
0            0                 889.80
1            0                 462.00
2            0                 595.50
3            0                 733.65
4            0                   0.00
(23474097, 19)

Missing values after merge:
request_datetime               0
on_scene_datetime              0
pickup_datetime                0
dropoff_datetime               0
PULocationID                   0
DOLocationID                   0
trip_miles                     0
trip_time                      0
tolls                          0
tips                           0
driver_pay                     0
PUBorough                      0
PUZone                         0
DOBorough                      0
DOZone                         0
time_from_request_to_pickup    0
day_of_week                    0
hour_bucket                    0
average_PU_to_DO_time          0
dtype: int64

5 random rows with relevant columns:
                                     PUZone           DOZone day_of_week  \
13964640                          Sunnyside  Jackson Heights    Thursday
15262736  University Heights/Morris Heights      Marble Hill      Sunday
14369101                           Woodside         Steinway      Friday
15110395                           Glendale    Cypress Hills    Saturday
7324224                          Ocean Hill     East Chelsea     Tuesday

          hour_bucket  average_PU_to_DO_time
13964640           15            1136.526316
15262736            8             514.250000
14369101           14             719.638889
15110395           22             699.066667
7324224             2            2054.166667

## Average Earnings For Pickup Zone (Per Hour Per Day)

In [4]:
import numpy as np

# Create actual calendar date so we don't group across many weeks/months
df['pickup_date'] = df['pickup_datetime'].dt.date

# -----------------------------
# Stage 1: daily zone-hour level
# -----------------------------
daily_zone_hour = df.groupby(
    ['PUZone', 'pickup_date', 'day_of_week', 'hour_bucket']
).agg(
    earliest_pickup_time=('pickup_datetime', 'min'),
    latest_dropoff_time=('dropoff_datetime', 'max'),
    total_driver_pay=('driver_pay', 'sum'),
    total_tips=('tips', 'sum'),
    trip_count=('pickup_datetime', 'count')
).reset_index()

daily_zone_hour['total_earnings'] = (
    daily_zone_hour['total_driver_pay'] + daily_zone_hour['total_tips']
)

daily_zone_hour['time_span_hours'] = (
    daily_zone_hour['latest_dropoff_time'] - daily_zone_hour['earliest_pickup_time']
).dt.total_seconds() / 3600

# Avoid bad/inflated values from tiny spans
daily_zone_hour = daily_zone_hour[daily_zone_hour['time_span_hours'] >= 0.10].copy()

daily_zone_hour['PU_driver_pay_per_hour'] = (
    daily_zone_hour['total_driver_pay'] / daily_zone_hour['time_span_hours']
)

daily_zone_hour['PU_tips_per_hour'] = (
    daily_zone_hour['total_tips'] / daily_zone_hour['time_span_hours']
)

daily_zone_hour['PU_total_earnings_per_hour'] = (
    daily_zone_hour['total_earnings'] / daily_zone_hour['time_span_hours']
)

# ------------------------------------------------
# Stage 2: average across same zone/day/hour pattern
# ------------------------------------------------
grouped_earnings = daily_zone_hour.groupby(
    ['PUZone', 'day_of_week', 'hour_bucket']
).agg(
    PU_avg_market_pay_per_hour=('PU_driver_pay_per_hour', 'mean'),
    PU_avg_market_tips_per_hour=('PU_tips_per_hour', 'mean'),
    PU_avg_market_total_earnings_per_hour=('PU_total_earnings_per_hour', 'mean'),
    avg_trip_count=('trip_count', 'mean'),
    avg_market_total_earnings=('total_earnings', 'mean'),
    avg_time_span_hours=('time_span_hours', 'mean'),
    sample_days=('pickup_date', 'nunique')
).reset_index()

print(grouped_earnings.head())
print(grouped_earnings.shape)

                    PUZone day_of_week  hour_bucket  \
0  Allerton/Pelham Gardens      Friday            0
1  Allerton/Pelham Gardens      Friday            1
2  Allerton/Pelham Gardens      Friday            2
3  Allerton/Pelham Gardens      Friday            3
4  Allerton/Pelham Gardens      Friday            4

   PU_avg_market_pay_per_hour  PU_avg_market_tips_per_hour  \
0                  168.720444                     2.500901
1                  134.133291                     0.288376
2                   73.766992                     2.435331
3                  111.190888                     2.607120
4                  174.600358                     6.225114

   PU_avg_market_total_earnings_per_hour  avg_trip_count  \
0                             171.221346       14.333333
1                             134.421667       11.333333
2                              76.202324        3.888889
3                             113.798008        5.666667
4                             180.825472       12.666667

   avg_market_total_earnings  avg_time_span_hours  sample_days
0                 211.175556             1.210617            9
1                 161.113333             1.211049            9
2                  57.463333             0.776883            9
3                 127.088889             1.028117            9
4                 234.533333             1.325494            9
(42361, 10)

In [5]:
top_earnings_rows = grouped_earnings.sort_values(by='avg_market_total_earnings', ascending=False)
print(top_earnings_rows.head())

               PUZone day_of_week  hour_bucket  PU_avg_market_pay_per_hour  \
25470  Midtown Center   Wednesday           21                 9415.803542
25446  Midtown Center     Tuesday           21                 8805.930431
25469  Midtown Center   Wednesday           20                 7743.176833
25422  Midtown Center    Thursday           21                 7764.138911
25445  Midtown Center     Tuesday           20                 7207.968859

       PU_avg_market_tips_per_hour  PU_avg_market_total_earnings_per_hour  \
25470                   867.029439                           10282.832980
25446                   828.203561                            9634.133992
25469                   672.796941                            8415.973774
25422                   695.820579                            8459.959490
25445                   678.322154                            7886.291013

       avg_trip_count  avg_market_total_earnings  avg_time_span_hours  \
25470      686.750000               20095.022500             1.953264
25446      633.500000               18565.552500             1.924688
25469      617.000000               17367.030000             2.085938
25422      576.111111               17088.094444             1.989475
25445      594.750000               15234.733750             1.954687

       sample_days
25470            8
25446            8
25469            8
25422            9
25445            8

In [6]:
import numpy as np

# How frequently rides occur.
grouped_earnings['PU_trip_density_per_hour'] = (
    grouped_earnings['avg_trip_count'] /
    grouped_earnings['avg_time_span_hours']
)

# Trip Quality:
grouped_earnings['PU_avg_earnings_per_trip'] = (
    grouped_earnings['avg_market_total_earnings'] /
    grouped_earnings['avg_trip_count']
)

# Higher tipping neighborhoods.
grouped_earnings['PU_tip_ratio_per_trip'] = (
    grouped_earnings['PU_avg_market_tips_per_hour'] /
    grouped_earnings['PU_avg_market_total_earnings_per_hour']
)

grouped_earnings['PU_zone_opportunity_score'] = (
    grouped_earnings['PU_avg_market_total_earnings_per_hour']
    * np.log1p(grouped_earnings['PU_trip_density_per_hour'])
)

print(grouped_earnings.sample(5))

                                 PUZone day_of_week  hour_bucket  \
10908  East Concourse/Concourse Village    Saturday           22
34511                  South Ozone Park   Wednesday           22
36090                         Sunnyside    Saturday           17
14510                          Flatiron   Wednesday            0
7718                       Clinton Hill    Saturday           21

       PU_avg_market_pay_per_hour  PU_avg_market_tips_per_hour  \
10908                 1227.579789                    11.173138
34511                  706.726191                    14.394316
36090                 1700.019104                    87.329819
14510                  533.145259                    34.108229
7718                  2052.569504                   115.988669

       PU_avg_market_total_earnings_per_hour  avg_trip_count  \
10908                            1238.752927      133.111111
34511                             721.120507       80.000000
36090                            1787.348923      187.666667
14510                             567.253488       43.125000
7718                             2168.558172      221.333333

       avg_market_total_earnings  avg_time_span_hours  sample_days  \
10908                2049.655556             1.651296            9
34511                1179.048750             1.643160            8
36090                3306.991111             1.859599            9
14510                 878.961250             1.550764            8
7718                 3715.303333             1.708302            9

       PU_trip_density_per_hour  PU_avg_earnings_per_trip  \
10908                 80.610071                 15.398080
34511                 48.686685                 14.738109
36090                100.917827                 17.621622
14510                 27.808876                 20.381710
7718                 129.563316                 16.786009

       PU_tip_ratio_per_trip  PU_zone_opportunity_score
10908               0.009020                5452.931755
34511               0.019961                2816.507041
36090               0.048860                8264.999678
14510               0.060129                1906.359448
7718                0.053487               10564.908115

**Reasoning**:
The subtask requires calculating the mean of two columns from `grouped_earnings` and then dividing them to find a conversion factor. This can be done in a single code cell.

In [7]:
avg_pu_opportunity_score = grouped_earnings['PU_zone_opportunity_score'].mean()
avg_market_earnings = grouped_earnings['avg_market_total_earnings'].mean()

conversion_factor = avg_pu_opportunity_score / avg_market_earnings

print(f"Average PU Zone Opportunity Score: {avg_pu_opportunity_score}")
print(f"Average Market Total Earnings: {avg_market_earnings}")
print(f"Conversion Factor (Opportunity Score Index Units per Dollar): {conversion_factor}")

Average PU Zone Opportunity Score: 2828.870946205133
Average Market Total Earnings: 1226.2774065861172
Conversion Factor (Opportunity Score Index Units per Dollar): 2.3068768379909566

In [8]:
columns_to_merge = [
    'PUZone',
    'day_of_week',
    'hour_bucket',
    'PU_zone_opportunity_score',
    'PU_tip_ratio_per_trip',
    'PU_avg_earnings_per_trip',
    'PU_trip_density_per_hour',
    'PU_avg_market_total_earnings_per_hour'
]

df = pd.merge(
    df,
    grouped_earnings[columns_to_merge],
    on=['PUZone', 'day_of_week', 'hour_bucket'],
    how='left'
)

print(df.head())
print(df.shape)

     request_datetime   on_scene_datetime     pickup_datetime  \
0 2026-01-01 00:50:37 2026-01-01 00:52:31 2026-01-01 00:54:30
1 2026-01-01 00:09:12 2026-01-01 00:12:17 2026-01-01 00:12:39
2 2026-01-01 00:16:16 2026-01-01 00:29:33 2026-01-01 00:31:34
3 2026-01-01 00:29:54 2026-01-01 00:36:04 2026-01-01 00:36:32
4 2026-01-01 00:07:33 2026-01-01 00:10:16 2026-01-01 00:11:14

     dropoff_datetime  PULocationID  DOLocationID  trip_miles  trip_time  \
0 2026-01-01 01:13:23           262            79        4.30       1133
1 2026-01-01 00:22:42           195            52        1.89        604
2 2026-01-01 00:55:21            25           181        1.84       1427
3 2026-01-01 01:02:28           162           113        2.84       1556
4 2026-01-01 00:14:06            22            22        0.66        172

   tolls  tips  ...  time_from_request_to_pickup day_of_week hour_bucket  \
0    0.0  0.00  ...                        114.0    Thursday           0
1    0.0  0.00  ...                        185.0    Thursday           0
2    0.0  2.67  ...                        797.0    Thursday           0
3    0.0  0.00  ...                        370.0    Thursday           0
4    0.0  0.00  ...                        163.0    Thursday           0

  average_PU_to_DO_time pickup_date  PU_zone_opportunity_score  \
0                889.80  2026-01-01                1236.554982
1                462.00  2026-01-01                 888.858401
2                595.50  2026-01-01                4507.158215
3                733.65  2026-01-01                8867.655260
4                  0.00  2026-01-01                1156.820287

  PU_tip_ratio_per_trip  PU_avg_earnings_per_trip  PU_trip_density_per_hour  \
0              0.075450                 20.799915                 21.527813
1              0.040708                 25.626590                 14.649637
2              0.061008                 25.307699                 53.264152
3              0.065770                 19.167750                101.123596
4              0.032570                 13.702837                 27.691697

  PU_avg_market_total_earnings_per_hour
0                            396.999666
1                            323.168625
2                           1128.520754
3                           1916.840239
4                            344.639696

[5 rows x 25 columns]
(23474097, 25)

In [9]:
# Check for missing values after the merge
print("\nMissing values after merge:")
print(df.isnull().sum())

Missing values after merge:
request_datetime                          0
on_scene_datetime                         0
pickup_datetime                           0
dropoff_datetime                          0
PULocationID                              0
DOLocationID                              0
trip_miles                                0
trip_time                                 0
tolls                                     0
tips                                      0
driver_pay                                0
PUBorough                                 0
PUZone                                    0
DOBorough                                 0
DOZone                                    0
time_from_request_to_pickup               0
day_of_week                               0
hour_bucket                               0
average_PU_to_DO_time                     0
pickup_date                               0
PU_zone_opportunity_score                43
PU_tip_ratio_per_trip                    47
PU_avg_earnings_per_trip                 43
PU_trip_density_per_hour                 43
PU_avg_market_total_earnings_per_hour    43
dtype: int64

In [10]:
import pandas as pd

missing_tip_ratio_rows = df[df['PU_tip_ratio_per_trip'].isnull()]
print("Rows with missing PU_tip_ratio_per_trip:")

# Display all columns for the first 10 rows
with pd.option_context('display.max_columns', None, 'display.width', 1000):
    print(missing_tip_ratio_rows.head(10))

Rows with missing PU_tip_ratio_per_trip:
           request_datetime   on_scene_datetime     pickup_datetime    dropoff_datetime  PULocationID  DOLocationID  trip_miles  trip_time  tolls  tips  driver_pay      PUBorough                               PUZone      DOBorough                               DOZone  time_from_request_to_pickup day_of_week  hour_bucket  average_PU_to_DO_time pickup_date  PU_zone_opportunity_score  PU_tip_ratio_per_trip  PU_avg_earnings_per_trip  PU_trip_density_per_hour  PU_avg_market_total_earnings_per_hour
211648  2026-01-01 10:32:23 2026-01-01 10:34:39 2026-01-01 10:34:43 2026-01-01 10:40:39            99             5        1.46        356    0.0   3.0        5.72  Staten Island                      Freshkills Park  Staten Island                        Arden Heights                        136.0    Thursday           10                  356.0  2026-01-01                        NaN                    NaN                       NaN                       NaN                                    NaN
425907  2026-01-02 01:27:38 2026-01-02 01:43:53 2026-01-02 01:45:53 2026-01-02 01:49:08           154           154        0.80        194    0.0   0.0        4.52       Brooklyn      Marine Park/Floyd Bennett Field       Brooklyn      Marine Park/Floyd Bennett Field                        975.0      Friday            1                    0.0  2026-01-02                        NaN                    NaN                       NaN                       NaN                                    NaN
767187  2026-01-02 23:54:35 2026-01-03 00:06:35 2026-01-03 00:06:35 2026-01-03 00:11:26           253            70        1.94        291    0.0   0.0        8.20         Queens                        Willets Point         Queens                        East Elmhurst                        720.0      Friday           23                  291.0  2026-01-03                        NaN                    NaN                       NaN                       NaN                                    NaN
820898  2026-01-03 06:46:52 2026-01-03 06:50:34 2026-01-03 06:50:58 2026-01-03 06:56:36           253           138        2.49        337    0.0   1.0        6.79         Queens                        Willets Point         Queens                    LaGuardia Airport                        222.0    Saturday            6                  337.0  2026-01-03                        NaN                    NaN                       NaN                       NaN                                    NaN
1363712 2026-01-04 17:06:11 2026-01-04 17:28:38 2026-01-04 17:28:47 2026-01-04 17:31:12            27            27        0.84        145    0.0   0.0       12.73         Queens  Breezy Point/Fort Tilden/Riis Beach         Queens  Breezy Point/Fort Tilden/Riis Beach                       1347.0      Sunday           17                    0.0  2026-01-04                        0.0                    NaN                       0.0                  2.304738                                    0.0
1488529 2026-01-05 01:54:32 2026-01-05 02:01:22 2026-01-05 02:01:39 2026-01-05 02:06:42             8           223        0.80        303    0.0   1.0        4.48         Queens                         Astoria Park         Queens                             Steinway                        410.0      Monday            1                  303.0  2026-01-05                        NaN                    NaN                       NaN                       NaN                                    NaN
1529901 2026-01-05 07:35:25 2026-01-05 07:36:14 2026-01-05 07:37:00 2026-01-05 07:40:58           111           228        0.77        238    0.0   1.0        4.49       Brooklyn                  Green-Wood Cemetery       Brooklyn                     Sunset Park West                         49.0      Monday            7                  238.0  2026-01-05                        NaN                    NaN                       NaN                       NaN                                    NaN
1806505 2026-01-05 23:58:14 2026-01-06 00:00:10 2026-01-06 00:00:14 2026-01-06 00:05:34           253            70        1.74        321    0.0   1.0        5.68         Queens                        Willets Point         Queens                        East Elmhurst                        116.0      Monday           23                  321.0  2026-01-06                        NaN                    NaN                       NaN                       NaN                                    NaN
1808813 2026-01-06 01:20:41 2026-01-06 01:25:51 2026-01-06 01:25:55 2026-01-06 01:31:52           207           223        1.35        357    0.0   5.0        5.60         Queens     Saint Michaels Cemetery/Woodside         Queens                             Steinway                        310.0     Tuesday            1                  357.0  2026-01-06                        NaN                    NaN                       NaN                       NaN                                    NaN
1814228 2026-01-06 02:04:23 2026-01-06 02:22:04 2026-01-06 02:22:04 2026-01-06 02:27:36            27           201        2.74        332    0.0   0.0       14.31         Queens  Breezy Point/Fort Tilden/Riis Beach         Queens                        Rockaway Park                       1061.0     Tuesday            2                  332.0  2026-01-06                        NaN                    NaN                       NaN                       NaN                                    NaN

In [11]:
columns_with_missing = [
    'PU_zone_opportunity_score',
    'PU_tip_ratio_per_trip',
    'PU_avg_earnings_per_trip',
    'PU_trip_density_per_hour',
    'PU_avg_market_total_earnings_per_hour'
]

original_rows = df.shape[0]
df.dropna(subset=columns_with_missing, inplace=True)

print(f"Dropped {original_rows - df.shape[0]} rows with missing values.")
print(f"New DataFrame shape: {df.shape}")
print("Remaining missing values after dropping:")
print(df[columns_with_missing].isnull().sum())

Dropped 47 rows with missing values.
New DataFrame shape: (23474050, 25)
Remaining missing values after dropping:
PU_zone_opportunity_score                0
PU_tip_ratio_per_trip                    0
PU_avg_earnings_per_trip                 0
PU_trip_density_per_hour                 0
PU_avg_market_total_earnings_per_hour    0
dtype: int64

In [12]:
columns_to_merge_from_grouped_earnings = [
    'PUZone',
    'day_of_week',
    'hour_bucket',
    'PU_zone_opportunity_score',
    'PU_tip_ratio_per_trip',
    'PU_avg_earnings_per_trip',
    'PU_trip_density_per_hour',
    'PU_avg_market_total_earnings_per_hour'
]

# Create a temporary DataFrame for merging DOZone specific features
do_zone_metrics = grouped_earnings[columns_to_merge_from_grouped_earnings].copy()

# Rename PUZone to DOZone for merging on drop-off zone
do_zone_metrics.rename(columns={'PUZone': 'DOZone'}, inplace=True)

# Rename PU_ prefixed columns to DO_ prefixed columns
do_zone_metrics.rename(columns={
    'PU_zone_opportunity_score': 'DO_zone_opportunity_score',
    'PU_tip_ratio_per_trip': 'DO_tip_ratio_per_trip',
    'PU_avg_earnings_per_trip': 'DO_avg_earnings_per_trip',
    'PU_trip_density_per_hour': 'DO_trip_density_per_hour',
    'PU_avg_market_total_earnings_per_hour': 'DO_avg_market_total_earnings_per_hour'
}, inplace=True)

# Merge these new DOZone specific features into the main DataFrame
df = pd.merge(
    df,
    do_zone_metrics,
    on=['DOZone', 'day_of_week', 'hour_bucket'],
    how='left'
)

# Calculate the opportunity cost of relocation time
# The opportunity cost is the earnings lost in the PUZone during the relocation time.
# average_PU_to_DO_time is in seconds, so convert to hours by dividing by 3600.
relocation_opportunity_cost = df['PU_avg_market_total_earnings_per_hour'] * (df['average_PU_to_DO_time'] / 3600)

# Convert the relocation opportunity cost to 'opportunity score index units'
converted_relocation_opportunity_cost = relocation_opportunity_cost * conversion_factor
df['converted_relocation_opportunity_cost'] = converted_relocation_opportunity_cost

# Adjust the DO_zone_opportunity_score by subtracting the converted relocation opportunity cost
df['DO_zone_opportunity_score'] = df['DO_zone_opportunity_score'] - df['converted_relocation_opportunity_cost']

print(df[['PUZone', 'DOZone', 'day_of_week', 'hour_bucket', 'average_PU_to_DO_time', 'PU_avg_market_total_earnings_per_hour', 'converted_relocation_opportunity_cost', 'PU_zone_opportunity_score','DO_zone_opportunity_score']].head())
print(f"DataFrame shape after conversion: {df.shape}")

print(df.head())
print(df.shape)

# Check for missing values after the merge and adjustment
print("\nMissing values after merge and adjustment:")
print(df.isnull().sum())

             PUZone                   DOZone day_of_week  hour_bucket  \
0    Yorkville East             East Village    Thursday            0
1          Red Hook              Cobble Hill    Thursday            0
2       Boerum Hill               Park Slope    Thursday            0
3      Midtown East  Greenwich Village North    Thursday            0
4  Bensonhurst West         Bensonhurst West    Thursday            0

   average_PU_to_DO_time  PU_avg_market_total_earnings_per_hour  \
0                 889.80                             396.999666
1                 462.00                             323.168625
2                 595.50                            1128.520754
3                 733.65                            1916.840239
4                   0.00                             344.639696

   converted_relocation_opportunity_cost  PU_zone_opportunity_score  \
0                             226.362484                1236.554982
1                              95.673811                 888.858401
2                             430.638867                4507.158215
3                             901.149295                8867.655260
4                               0.000000                1156.820287

   DO_zone_opportunity_score
0               11120.060310
1                 570.650786
2                7165.893521
3                2147.058233
4                1156.820287
DataFrame shape after conversion: (23474050, 31)
     request_datetime   on_scene_datetime     pickup_datetime  \
0 2026-01-01 00:50:37 2026-01-01 00:52:31 2026-01-01 00:54:30
1 2026-01-01 00:09:12 2026-01-01 00:12:17 2026-01-01 00:12:39
2 2026-01-01 00:16:16 2026-01-01 00:29:33 2026-01-01 00:31:34
3 2026-01-01 00:29:54 2026-01-01 00:36:04 2026-01-01 00:36:32
4 2026-01-01 00:07:33 2026-01-01 00:10:16 2026-01-01 00:11:14

     dropoff_datetime  PULocationID  DOLocationID  trip_miles  trip_time  \
0 2026-01-01 01:13:23           262            79        4.30       1133
1 2026-01-01 00:22:42           195            52        1.89        604
2 2026-01-01 00:55:21            25           181        1.84       1427
3 2026-01-01 01:02:28           162           113        2.84       1556
4 2026-01-01 00:14:06            22            22        0.66        172

   tolls  tips  ...  PU_tip_ratio_per_trip PU_avg_earnings_per_trip  \
0    0.0  0.00  ...               0.075450                20.799915
1    0.0  0.00  ...               0.040708                25.626590
2    0.0  2.67  ...               0.061008                25.307699
3    0.0  0.00  ...               0.065770                19.167750
4    0.0  0.00  ...               0.032570                13.702837

  PU_trip_density_per_hour PU_avg_market_total_earnings_per_hour  \
0                21.527813                            396.999666
1                14.649637                            323.168625
2                53.264152                           1128.520754
3               101.123596                           1916.840239
4                27.691697                            344.639696

  DO_zone_opportunity_score  DO_tip_ratio_per_trip DO_avg_earnings_per_trip  \
0              11120.060310               0.055124                21.464324
1                570.650786               0.059132                27.429754
2               7165.893521               0.052103                23.492268
3               2147.058233               0.045348                22.835190
4               1156.820287               0.032570                13.702837

   DO_trip_density_per_hour  DO_avg_market_total_earnings_per_hour  \
0                124.674193                            2347.361177
1                 11.540584                             263.476661
2                 85.523603                            1703.099052
3                 41.113543                             814.948261
4                 27.691697                             344.639696

  converted_relocation_opportunity_cost
0                            226.362484
1                             95.673811
2                            430.638867
3                            901.149295
4                              0.000000

[5 rows x 31 columns]
(23474050, 31)

Missing values after merge and adjustment:
request_datetime                              0
on_scene_datetime                             0
pickup_datetime                               0
dropoff_datetime                              0
PULocationID                                  0
DOLocationID                                  0
trip_miles                                    0
trip_time                                     0
tolls                                         0
tips                                          0
driver_pay                                    0
PUBorough                                     0
PUZone                                        0
DOBorough                                     0
DOZone                                        0
time_from_request_to_pickup                   0
day_of_week                                   0
hour_bucket                                   0
average_PU_to_DO_time                         0
pickup_date                                   0
PU_zone_opportunity_score                     0
PU_tip_ratio_per_trip                         0
PU_avg_earnings_per_trip                      0
PU_trip_density_per_hour                      0
PU_avg_market_total_earnings_per_hour         0
DO_zone_opportunity_score                957187
DO_tip_ratio_per_trip                    957200
DO_avg_earnings_per_trip                 957187
DO_trip_density_per_hour                 957187
DO_avg_market_total_earnings_per_hour    957187
converted_relocation_opportunity_cost         0
dtype: int64

**Reasoning**:
The subtask requires converting the `relocation_opportunity_cost` into 'opportunity score index units' using the previously calculated `conversion_factor`. This step performs that multiplication.

In [13]:
import pandas as pd

# Identify columns with missing 'DO_' values (from previous output, they all have the same count)
missing_do_cols = [
    'DO_zone_opportunity_score',
    'DO_tip_ratio_per_trip',
    'DO_avg_earnings_per_trip',
    'DO_trip_density_per_hour',
    'DO_avg_market_total_earnings_per_hour'
]

# Filter DataFrame to get rows where 'DO_zone_opportunity_score' is null (implies others are also null)
missing_do_rows = df[df['DO_zone_opportunity_score'].isnull()]

print(f"Displaying 10 random rows where 'DO_' prefixed columns are null:")

# Display all columns for the 10 random rows
with pd.option_context('display.max_columns', None, 'display.width', 1000):
    print(missing_do_rows.sample(10))

Displaying 10 random rows where 'DO_' prefixed columns are null:
            request_datetime   on_scene_datetime     pickup_datetime    dropoff_datetime  PULocationID  DOLocationID  trip_miles  trip_time  tolls   tips  driver_pay  PUBorough                     PUZone DOBorough             DOZone  time_from_request_to_pickup day_of_week  hour_bucket  average_PU_to_DO_time pickup_date  PU_zone_opportunity_score  PU_tip_ratio_per_trip  PU_avg_earnings_per_trip  PU_trip_density_per_hour  PU_avg_market_total_earnings_per_hour  DO_zone_opportunity_score  DO_tip_ratio_per_trip  DO_avg_earnings_per_trip  DO_trip_density_per_hour  DO_avg_market_total_earnings_per_hour  converted_relocation_opportunity_cost
20867281 2026-02-21 21:33:53 2026-02-21 21:36:33 2026-02-21 21:37:48 2026-02-21 22:13:39            62           132       10.17       2152   0.00   0.00       36.25   Brooklyn        Crown Heights South    Queens        JFK Airport                        160.0    Saturday           21            2345.250000  2026-02-21                4400.371924               0.030151                 17.061538                 62.124594                            1061.581344                        NaN                    NaN                       NaN                       NaN                                    NaN                            1595.380687
16110929 2026-02-10 07:59:15 2026-02-10 08:01:58 2026-02-10 08:02:05 2026-02-10 08:24:20           141           138        8.60       1336   7.46   0.00       35.62  Manhattan            Lenox Hill West    Queens  LaGuardia Airport                        163.0     Tuesday            7            1609.742268  2026-02-10                9013.992391               0.066423                 20.465211                 94.917606                            1975.241158                        NaN                    NaN                       NaN                       NaN                                    NaN                            2037.503586
2499058  2026-01-08 04:30:00 2026-01-08 04:17:02 2026-01-08 04:21:30 2026-01-08 04:50:55            61           132       10.44       1765   0.00   0.00       33.09   Brooklyn        Crown Heights North    Queens        JFK Airport                       -778.0    Thursday            4            1943.827957  2026-01-08                4365.274551               0.037809                 21.582236                 49.632636                            1112.286247                        NaN                    NaN                       NaN                       NaN                                    NaN                            1385.467362
10659460 2026-01-28 19:15:04 2026-01-28 19:31:30 2026-01-28 19:32:00 2026-01-28 19:51:19           162           138        9.29       1158   7.46  13.50       33.68  Manhattan               Midtown East    Queens  LaGuardia Airport                        986.0   Wednesday           19            1554.228571  2026-01-28               20389.038846               0.085494                 23.348999                169.528892                            3967.584514                        NaN                    NaN                       NaN                       NaN                                    NaN                            3951.509066
20181327 2026-02-20 11:14:44 2026-02-20 11:19:42 2026-02-20 11:20:15 2026-02-20 11:50:25           107           138        9.65       1810   7.46   0.00       31.86  Manhattan                   Gramercy    Queens  LaGuardia Airport                        298.0      Friday           11            1740.295082  2026-02-20                5522.425047               0.071471                 22.340125                 59.848751                            1344.181860                        NaN                    NaN                       NaN                       NaN                                    NaN                            1499.004136
6168196  2026-01-17 06:30:32 2026-01-17 06:34:14 2026-01-17 06:34:52 2026-01-17 06:52:55           256           138        8.29       1084   0.00   0.00       22.19   Brooklyn  Williamsburg (South Side)    Queens  LaGuardia Airport                        222.0    Saturday            6            1099.181818  2026-01-17                2774.766247               0.047898                 20.692012                 36.833290                             763.727389                        NaN                    NaN                       NaN                       NaN                                    NaN                             537.935009
9773197  2026-01-26 13:34:41 2026-01-26 13:38:40 2026-01-26 13:39:24 2026-01-26 14:00:32            33           138       10.88       1268   0.00   0.00       28.65   Brooklyn           Brooklyn Heights    Queens  LaGuardia Airport                        239.0      Monday           13            1742.678571  2026-01-26                3112.205276               0.093224                 24.565571                 36.291475                             860.018679                        NaN                    NaN                       NaN                       NaN                                    NaN                             960.388792
1048201  2026-01-03 19:22:07 2026-01-03 19:23:57 2026-01-03 19:24:30 2026-01-03 20:18:57           189           132       21.54       3267   0.00   0.00       62.61   Brooklyn           Prospect Heights    Queens        JFK Airport                        110.0    Saturday           19            2769.235294  2026-01-03                8499.887703               0.062193                 20.478320                 92.362693                            1873.669790                        NaN                    NaN                       NaN                       NaN                                    NaN                            3324.871156
9943941  2026-01-27 03:30:00 2026-01-27 03:28:07 2026-01-27 03:29:47 2026-01-27 04:06:30            48           132       17.82       2203   0.00   0.00       57.60  Manhattan               Clinton East    Queens        JFK Airport                       -113.0     Tuesday            3            2056.730769  2026-01-27                1979.354630               0.060787                 24.278792                 25.010491                             607.443504                        NaN                    NaN                       NaN                       NaN                                    NaN                             800.580937
19178564 2026-02-17 17:58:27 2026-02-17 17:59:53 2026-02-17 18:00:21 2026-02-17 18:34:43           233           138        9.84       2061   7.46  10.82       34.85  Manhattan        UN/Turtle Bay South    Queens  LaGuardia Airport                         86.0     Tuesday           17            1797.333333  2026-02-17                6367.156100               0.076531                 26.251886                 59.058443                            1554.740286                        NaN                    NaN                       NaN                       NaN                                    NaN                            1790.640441

### Handle Missing DO Zone Metrics

Given that the missing values in the `DO_` prefixed columns primarily correspond to airport zones where we do not want to recommend relocation, we will fill these `NaN` values with `0`. This effectively assigns a zero opportunity score to these drop-off zones, ensuring they are not considered favorable for a driver's next pickup.

In [14]:
# Fill missing values in DO_ prefixed columns with 0
df[missing_do_cols] = df[missing_do_cols].fillna(0)

print("Missing values after filling DO_ prefixed columns with 0:")
print(df[missing_do_cols].isnull().sum())

# Verify a few random rows to ensure the fill operation was successful
print("\n5 random rows from DO_zone_opportunity_score column after filling NaN with 0:")
print(df[['DOZone', 'day_of_week', 'hour_bucket', 'DO_zone_opportunity_score']].sample(5))

Missing values after filling DO_ prefixed columns with 0:
DO_zone_opportunity_score                0
DO_tip_ratio_per_trip                    0
DO_avg_earnings_per_trip                 0
DO_trip_density_per_hour                 0
DO_avg_market_total_earnings_per_hour    0
dtype: int64

5 random rows from DO_zone_opportunity_score column after filling NaN with 0:
                                 DOZone day_of_week  hour_bucket  \
21051743         Charleston/Tottenville      Sunday            8
10350806                    JFK Airport   Wednesday            2
14810687      Williamsburg (North Side)    Saturday           12
14546764                      Homecrest      Friday           21
16271681  Meatpacking/West Village West     Tuesday           16

          DO_zone_opportunity_score
21051743                 199.235161
10350806                   0.000000
14810687                9954.684965
14546764                1437.520547
16271681                2893.109173

In [15]:
# Columns to display for a more comprehensive comparison
display_columns = [
    'PUZone',
    'DOZone',
    'day_of_week',
    'hour_bucket',
    'average_PU_to_DO_time',
    'PU_zone_opportunity_score',
    'DO_zone_opportunity_score',
    'PU_avg_market_total_earnings_per_hour',
    'DO_avg_market_total_earnings_per_hour',
    'PU_tip_ratio_per_trip',
    'DO_tip_ratio_per_trip'
]

# 5 random rows where DO opportunity score was higher than PU opportunity score
higher_do_score = df[df['DO_zone_opportunity_score'] > df['PU_zone_opportunity_score']]
print(f"\nNumber of rows where DO opportunity score is HIGHER than PU opportunity score: {higher_do_score.shape[0]}")
print("5 random rows where DO opportunity score is HIGHER than PU opportunity score:")
with pd.option_context('display.max_columns', None, 'display.width', 1000):
    print(higher_do_score.sample(5)[display_columns])

# 5 random rows where DO opportunity score was lower than PU opportunity score
lower_do_score = df[df['DO_zone_opportunity_score'] < df['PU_zone_opportunity_score']]
print(f"\nNumber of rows where DO opportunity score is LOWER than PU opportunity score: {lower_do_score.shape[0]}")
print("5 random rows where DO opportunity score is LOWER than PU opportunity score:")
with pd.option_context('display.max_columns', None, 'display.width', 1000):
    print(lower_do_score.sample(5)[display_columns])

# 5 random rows where DO opportunity score was the same as PU opportunity score
same_do_score = df[df['DO_zone_opportunity_score'] == df['PU_zone_opportunity_score']]
print(f"\nNumber of rows where DO opportunity score is the SAME as PU opportunity score: {same_do_score.shape[0]}")
print("5 random rows where DO opportunity score is the SAME as PU opportunity score:")
with pd.option_context('display.max_columns', None, 'display.width', 1000):
    print(same_do_score.sample(5)[display_columns])

Number of rows where DO opportunity score is HIGHER than PU opportunity score: 8179969
5 random rows where DO opportunity score is HIGHER than PU opportunity score:
                       PUZone                 DOZone day_of_week  hour_bucket  average_PU_to_DO_time  PU_zone_opportunity_score  DO_zone_opportunity_score  PU_avg_market_total_earnings_per_hour  DO_avg_market_total_earnings_per_hour  PU_tip_ratio_per_trip  DO_tip_ratio_per_trip
1823360      Sunset Park East              Bay Ridge     Tuesday            5             501.400000                1032.164640                2268.866331                             354.441488                             708.257686               0.040500               0.090283
15513208        Cypress Hills          East New York      Sunday           19             556.941176                2111.694506                7793.179280                             574.929391                            1712.237332               0.021221               0.011961
4373462   Lincoln Square West    Lincoln Square East      Monday           17             418.153846                4031.045050                4898.133056                            1010.658728                            1260.947300               0.078017               0.083952
22065764  Lincoln Square West  Upper West Side South   Wednesday           21             367.896552                2219.319052                5073.938209                             641.059082                            1275.858573               0.072900               0.065290
19728829            Glen Oaks           Saint Albans    Thursday            9            1190.200000                 649.689444                3431.307094                             265.217494                             892.171914               0.058002               0.018402

Number of rows where DO opportunity score is LOWER than PU opportunity score: 13083254
5 random rows where DO opportunity score is LOWER than PU opportunity score:
                                  PUZone             DOZone day_of_week  hour_bucket  average_PU_to_DO_time  PU_zone_opportunity_score  DO_zone_opportunity_score  PU_avg_market_total_earnings_per_hour  DO_avg_market_total_earnings_per_hour  PU_tip_ratio_per_trip  DO_tip_ratio_per_trip
976295               Little Italy/NoLiTa       Clinton Hill    Saturday           16            1447.086957               12401.115762                5937.117920                            2599.318628                            1826.188129               0.062562               0.055502
17460225           Upper East Side North    Lenox Hill West      Friday           13             757.728814                8152.292452                4961.648130                            1863.851515                            1438.565062               0.086845               0.065993
17894687  Long Island City/Hunters Point  East Williamsburg    Saturday           11            1123.720000               10220.687336                7278.344355                            2120.532561                            1862.474441               0.045275               0.055533
13475442                    Forest Hills    Jamaica Estates   Wednesday            9            1024.727273                7509.193397                 879.600607                            1655.795127                             575.388343               0.055624               0.032334
5014257                East Harlem South  Crotona Park East   Wednesday           12            1380.000000                5462.858154                 276.810033                            1310.784687                             424.560523               0.059221               0.016657

Number of rows where DO opportunity score is the SAME as PU opportunity score: 2210827
5 random rows where DO opportunity score is the SAME as PU opportunity score:
                           PUZone                   DOZone day_of_week  hour_bucket  average_PU_to_DO_time  PU_zone_opportunity_score  DO_zone_opportunity_score  PU_avg_market_total_earnings_per_hour  DO_avg_market_total_earnings_per_hour  PU_tip_ratio_per_trip  DO_tip_ratio_per_trip
21911907     Flatbush/Ditmas Park     Flatbush/Ditmas Park   Wednesday           14                    0.0                6044.576434                6044.576434                            1402.194987                            1402.194987               0.028231               0.028231
20631676  Greenwich Village North  Greenwich Village North    Saturday           11                    0.0                5840.222845                5840.222845                            1325.526461                            1325.526461               0.086528               0.086528
10686030         Sunset Park East         Sunset Park East   Wednesday           20                    0.0                1809.665547                1809.665547                             507.496757                             507.496757               0.032595               0.032595
14773271          Jackson Heights          Jackson Heights    Saturday           11                    0.0                7670.595457                7670.595457                            1651.515160                            1651.515160               0.043547               0.043547
20140783         Bensonhurst West         Bensonhurst West      Friday            9                    0.0                4291.628459                4291.628459                            1023.274476                            1023.274476               0.043017               0.043017

## Step 3

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23474050 entries, 0 to 23474049
Data columns (total 31 columns):
 #   Column                                 Dtype
---  ------                                 -----
 0   request_datetime                       datetime64[us]
 1   on_scene_datetime                      datetime64[us]
 2   pickup_datetime                        datetime64[us]
 3   dropoff_datetime                       datetime64[us]
 4   PULocationID                           int32
 5   DOLocationID                           int32
 6   trip_miles                             float64
 7   trip_time                              int64
 8   tolls                                  float64
 9   tips                                   float64
 10  driver_pay                             float64
 11  PUBorough                              object
 12  PUZone                                 object
 13  DOBorough                              object
 14  DOZone                                 object
 15  time_from_request_to_pickup            float64
 16  day_of_week                            object
 17  hour_bucket                            int32
 18  average_PU_to_DO_time                  float64
 19  pickup_date                            object
 20  PU_zone_opportunity_score              float64
 21  PU_tip_ratio_per_trip                  float64
 22  PU_avg_earnings_per_trip               float64
 23  PU_trip_density_per_hour               float64
 24  PU_avg_market_total_earnings_per_hour  float64
 25  DO_zone_opportunity_score              float64
 26  DO_tip_ratio_per_trip                  float64
 27  DO_avg_earnings_per_trip               float64
 28  DO_trip_density_per_hour               float64
 29  DO_avg_market_total_earnings_per_hour  float64
 30  converted_relocation_opportunity_cost  float64
dtypes: datetime64[us](4), float64(17), int32(3), int64(1), object(6)
memory usage: 5.2+ GB

In [17]:
df['day_of_week_numeric'] = df['request_datetime'].dt.dayofweek

columns_to_drop = [
    'request_datetime',
    'on_scene_datetime',
    'pickup_datetime',
    'dropoff_datetime',
    'pickup_date',
    'converted_relocation_opportunity_cost',
    'day_of_week' # Add the original object-type day_of_week to be dropped
]

df = df.drop(columns=columns_to_drop)

print("DataFrame after dropping columns and converting day_of_week:")
print(df.info())
df.head()

DataFrame after dropping columns and converting day_of_week:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23474050 entries, 0 to 23474049
Data columns (total 25 columns):
 #   Column                                 Dtype
---  ------                                 -----
 0   PULocationID                           int32
 1   DOLocationID                           int32
 2   trip_miles                             float64
 3   trip_time                              int64
 4   tolls                                  float64
 5   tips                                   float64
 6   driver_pay                             float64
 7   PUBorough                              object
 8   PUZone                                 object
 9   DOBorough                              object
 10  DOZone                                 object
 11  time_from_request_to_pickup            float64
 12  hour_bucket                            int32
 13  average_PU_to_DO_time                  float64
 14  PU_zone_opportunity_score              float64
 15  PU_tip_ratio_per_trip                  float64
 16  PU_avg_earnings_per_trip               float64
 17  PU_trip_density_per_hour               float64
 18  PU_avg_market_total_earnings_per_hour  float64
 19  DO_zone_opportunity_score              float64
 20  DO_tip_ratio_per_trip                  float64
 21  DO_avg_earnings_per_trip               float64
 22  DO_trip_density_per_hour               float64
 23  DO_avg_market_total_earnings_per_hour  float64
 24  day_of_week_numeric                    int32
dtypes: float64(16), int32(4), int64(1), object(4)
memory usage: 4.0+ GB
None

,PULocationID,DOLocationID,trip_miles,trip_time,tolls,tips,driver_pay,PUBorough,PUZone,DOBorough,...,PU_tip_ratio_per_trip,PU_avg_earnings_per_trip,PU_trip_density_per_hour,PU_avg_market_total_earnings_per_hour,DO_zone_opportunity_score,DO_tip_ratio_per_trip,DO_avg_earnings_per_trip,DO_trip_density_per_hour,DO_avg_market_total_earnings_per_hour,day_of_week_numeric
0,262,79,4.30,1133,0.0,0.00,21.10,Manhattan,Yorkville East,Manhattan,...,0.075450,20.799915,21.527813,396.999666,11120.060310,0.055124,21.464324,124.674193,2347.361177,3
1,195,52,1.89,604,0.0,0.00,9.10,Brooklyn,Red Hook,Brooklyn,...,0.040708,25.626590,14.649637,323.168625,570.650786,0.059132,27.429754,11.540584,263.476661,3
2,25,181,1.84,1427,0.0,2.67,21.94,Brooklyn,Boerum Hill,Brooklyn,...,0.061008,25.307699,53.264152,1128.520754,7165.893521,0.052103,23.492268,85.523603,1703.099052,3
3,162,113,2.84,1556,0.0,0.00,20.90,Manhattan,Midtown East,Manhattan,...,0.065770,19.167750,101.123596,1916.840239,2147.058233,0.045348,22.835190,41.113543,814.948261,3
4,22,22,0.66,172,0.0,0.00,4.31,Brooklyn,Bensonhurst West,Brooklyn,...,0.032570,13.702837,27.691697,344.639696,1156.820287,0.032570,13.702837,27.691697,344.639696,3

In [18]:
agg_df = (
    df.groupby([
        'PULocationID',
        'DOLocationID',
        'hour_bucket',
        'day_of_week_numeric'
    ])
    .agg({
        'average_PU_to_DO_time': 'mean',
        'PU_avg_market_total_earnings_per_hour': 'mean',
        'DO_avg_market_total_earnings_per_hour': 'mean',
        'PU_trip_density_per_hour': 'mean',
        'DO_trip_density_per_hour': 'mean',
        'PU_zone_opportunity_score': 'mean',
        'DO_zone_opportunity_score': 'mean'
    })
    .reset_index()
)

print("Aggregated DataFrame Head:")
display(agg_df.head())

Aggregated DataFrame Head:

,PULocationID,DOLocationID,hour_bucket,day_of_week_numeric,average_PU_to_DO_time,PU_avg_market_total_earnings_per_hour,DO_avg_market_total_earnings_per_hour,PU_trip_density_per_hour,DO_trip_density_per_hour,PU_zone_opportunity_score,DO_zone_opportunity_score
0,2,10,8,0,805.0,69.227329,859.841769,4.472050,48.371309,117.662456,3317.130280
1,2,10,15,4,1573.0,62.982835,704.553860,2.288620,42.443425,74.979061,2593.711105
2,2,10,16,3,2032.0,62.347841,688.789209,2.532536,43.111691,78.683976,2527.071843
3,2,10,17,2,1811.0,80.062613,604.634029,2.663707,38.049071,103.959339,2122.962694
4,2,10,18,3,1345.0,67.225116,610.723849,2.421796,35.518063,82.698026,2139.326920

In [19]:
agg_df['travel_penalty'] = (
    (agg_df['average_PU_to_DO_time'] / 3600) # Convert seconds to hours
    * agg_df['PU_avg_market_total_earnings_per_hour']
)

print("Aggregated DataFrame with Travel Penalty Head:")
display(agg_df.head())

Aggregated DataFrame with Travel Penalty Head:

,PULocationID,DOLocationID,hour_bucket,day_of_week_numeric,average_PU_to_DO_time,PU_avg_market_total_earnings_per_hour,DO_avg_market_total_earnings_per_hour,PU_trip_density_per_hour,DO_trip_density_per_hour,PU_zone_opportunity_score,DO_zone_opportunity_score,travel_penalty
0,2,10,8,0,805.0,69.227329,859.841769,4.472050,48.371309,117.662456,3317.130280,15.480000
1,2,10,15,4,1573.0,62.982835,704.553860,2.288620,42.443425,74.979061,2593.711105,27.520000
2,2,10,16,3,2032.0,62.347841,688.789209,2.532536,43.111691,78.683976,2527.071843,35.191893
3,2,10,17,2,1811.0,80.062613,604.634029,2.663707,38.049071,103.959339,2122.962694,40.275942
4,2,10,18,3,1345.0,67.225116,610.723849,2.421796,35.518063,82.698026,2139.326920,25.116050

In [20]:
agg_df['net_gain'] = (
    agg_df['DO_avg_market_total_earnings_per_hour']
    - agg_df['PU_avg_market_total_earnings_per_hour']
    - agg_df['travel_penalty']
)

print("Aggregated DataFrame with Net Gain Head:")
display(agg_df.head())

Aggregated DataFrame with Net Gain Head:

,PULocationID,DOLocationID,hour_bucket,day_of_week_numeric,average_PU_to_DO_time,PU_avg_market_total_earnings_per_hour,DO_avg_market_total_earnings_per_hour,PU_trip_density_per_hour,DO_trip_density_per_hour,PU_zone_opportunity_score,DO_zone_opportunity_score,travel_penalty,net_gain
0,2,10,8,0,805.0,69.227329,859.841769,4.472050,48.371309,117.662456,3317.130280,15.480000,775.134440
1,2,10,15,4,1573.0,62.982835,704.553860,2.288620,42.443425,74.979061,2593.711105,27.520000,614.051025
2,2,10,16,3,2032.0,62.347841,688.789209,2.532536,43.111691,78.683976,2527.071843,35.191893,591.249474
3,2,10,17,2,1811.0,80.062613,604.634029,2.663707,38.049071,103.959339,2122.962694,40.275942,484.295474
4,2,10,18,3,1345.0,67.225116,610.723849,2.421796,35.518063,82.698026,2139.326920,25.116050,518.382682

In [21]:
stay_rows = (
    agg_df.groupby([
        'PULocationID',
        'hour_bucket',
        'day_of_week_numeric'
    ])
    .first() # Take the first occurrence for each group as a base
    .reset_index()
)

stay_rows['DOLocationID'] = stay_rows['PULocationID']
stay_rows['average_PU_to_DO_time'] = 0
stay_rows['travel_penalty'] = 0

stay_rows['DO_avg_market_total_earnings_per_hour'] = (
    stay_rows['PU_avg_market_total_earnings_per_hour']
)

stay_rows['net_gain'] = 0

print("Stay-Put Rows Head:")
display(stay_rows.head())

Stay-Put Rows Head:

,PULocationID,hour_bucket,day_of_week_numeric,DOLocationID,average_PU_to_DO_time,PU_avg_market_total_earnings_per_hour,DO_avg_market_total_earnings_per_hour,PU_trip_density_per_hour,DO_trip_density_per_hour,PU_zone_opportunity_score,DO_zone_opportunity_score,travel_penalty,net_gain
0,2,1,0,2,0,62.481876,62.481876,2.558635,8.792860,79.313066,236.113411,0,0
1,2,6,4,2,0,82.354286,82.354286,6.857143,5.047735,169.767022,299.423956,0,0
2,2,8,0,2,0,69.227329,69.227329,4.472050,48.371309,117.662456,3317.130280,0,0
3,2,8,3,2,0,64.173913,64.173913,4.347826,8.652869,107.599767,557.654012,0,0
4,2,9,2,2,0,105.306733,105.306733,8.977556,18.864806,242.241099,1090.199017,0,0

In [22]:
training_table = pd.concat([
    agg_df,
    stay_rows
], ignore_index=True)

print("Final Training Table Head:")
display(training_table.head())

Final Training Table Head:

,PULocationID,DOLocationID,hour_bucket,day_of_week_numeric,average_PU_to_DO_time,PU_avg_market_total_earnings_per_hour,DO_avg_market_total_earnings_per_hour,PU_trip_density_per_hour,DO_trip_density_per_hour,PU_zone_opportunity_score,DO_zone_opportunity_score,travel_penalty,net_gain
0,2,10,8,0,805.0,69.227329,859.841769,4.472050,48.371309,117.662456,3317.130280,15.480000,775.134440
1,2,10,15,4,1573.0,62.982835,704.553860,2.288620,42.443425,74.979061,2593.711105,27.520000,614.051025
2,2,10,16,3,2032.0,62.347841,688.789209,2.532536,43.111691,78.683976,2527.071843,35.191893,591.249474
3,2,10,17,2,1811.0,80.062613,604.634029,2.663707,38.049071,103.959339,2122.962694,40.275942,484.295474
4,2,10,18,3,1345.0,67.225116,610.723849,2.421796,35.518063,82.698026,2139.326920,25.116050,518.382682

In [23]:
training_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3185960 entries, 0 to 3185959
Data columns (total 13 columns):
 #   Column                                 Dtype
---  ------                                 -----
 0   PULocationID                           int32
 1   DOLocationID                           int32
 2   hour_bucket                            int32
 3   day_of_week_numeric                    int32
 4   average_PU_to_DO_time                  float64
 5   PU_avg_market_total_earnings_per_hour  float64
 6   DO_avg_market_total_earnings_per_hour  float64
 7   PU_trip_density_per_hour               float64
 8   DO_trip_density_per_hour               float64
 9   PU_zone_opportunity_score              float64
 10  DO_zone_opportunity_score              float64
 11  travel_penalty                         float64
 12  net_gain                               float64
dtypes: float64(9), int32(4)
memory usage: 267.4 MB

## Exporting DataFrames

In [24]:
# Export the main processed training_table 'training_table' to Parquet
output_training_table_path = '/content/uber_trips_training.parquet'
training_table.to_parquet(output_training_table_path, index=False)
print(f"Main DataFrame exported to: {output_training_table_path}")

Main DataFrame exported to: /content/uber_trips_training.parquet

### Export for Zone to Zone Lookups

In [ ]:
# # Export 'average_trip_time_by_route_time' for zone-to-zone lookups
# output_avg_trip_time_path = '/content/avg_trip_time_zone_to_zone.parquet'
# average_trip_time_by_route_time.to_parquet(output_avg_trip_time_path, index=False)
# print(f"Average trip time DataFrame exported to: {output_avg_trip_time_path}")

### Export for Earnings Estimations

In [ ]:
# # Export 'grouped_earnings' for earnings estimations
# output_grouped_earnings_path = '/content/avg_earnings_zone_hour.parquet'
# grouped_earnings.to_parquet(output_grouped_earnings_path, index=False)
# print(f"Grouped earnings DataFrame exported to: {output_grouped_earnings_path}")